# What is Jupyter Notebooks?

Jupyter is a web-based interactive development environment that supports multiple programming languages, however most commonly used with the Python programming language.

The interactive environment that Jupyter provides enables students, scientists, and researchers to create reproducible analysis and formulate a story within a single document.

Lets take a look at an example of a completed Jupyter Notebook: [Example Notebook](http://nbviewer.jupyter.org/github/cossatot/lanf_earthquake_likelihood/blob/master/notebooks/lanf_manuscript_notebook.ipynb)

In [1]:
# Import seaborn
import seaborn as sns

# Load an example dataset
tips = sns.load_dataset("tips")

tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [2]:
type(tips)

pandas.core.frame.DataFrame

### Jupyter Notebook Features

* File Browser
* Markdown Cells & Syntax
* Kernels, Variables, & Environment
* Command vs. Edit Mode & Shortcuts

### What is Markdown?

Markdown is a markup language that uses plain text formatting syntax.  This means that we can modify the formatting our text with the use of various symbols on our keyboard as indicators.

Some examples include:

* Headers
* Text modifications such as italics and bold
* Ordered and Unordered lists
* Links
* Tables
* Images
* Etc.

Now I'll showcase some examples of how this formatting is done:

Headers:

# H1 Main H1
## H2 Secondary Heading
### H3
#### H4
##### H5
###### H6

Text modifications:

Emphasis, aka italics, with *asterisks* or _underscores_.

Strong **emphasis**, aka bold, with **asterisks** or __underscores__.

**_Combined emphasis_** with **asterisks and _underscores_**.

~~Strikethrough~~ uses two tildes. ~~Scratch this.~~

Text modifications:

Emphasis, aka italics, with *asterisks* or _underscores_.

Strong emphasis, aka bold, with **asterisks** or __underscores__.

Combined emphasis with __asterisks and _underscores___.

Strikethrough uses two tildes. ~~Scratch this.~~

Lists:

1. Testing the actual
  1. another
2. Another item
  * Unordered sub-list. 
1. Actual numbers don't matter, just that it's a number
  1. Ordered sub-list
4. And another item.

* Unordered list can use asterisks
- Or minuses
+ Or pluses

Links:

http://www.umich.edu

<http://www.youtube.com>
<google.com>

[the youtube site] (http://www.youtube.com)

To look into more examples of Markdown syntax and features such as tables, images, etc. head to the following link: [Markdown Reference](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

### Kernels, Variables, and Environment

A notebook kernel is a “computational engine” that executes the code contained in a Notebook document. There are kernels for various programming languages, however we are solely using the python kernel which executes python code.

When a notebook is opened, the associated kernel is automatically launched for our convenience.

In [3]:
### Hello
print ("hello be welcome to our home- Hello Saiful")

hello be welcome to our home- Hello Saiful

In [4]:
x=1755
print ("x has been set to " + str(x))

x has been set to 1755

In [5]:
print(x)

1755

A kernel is the back-end of our notebook which not only executes our python code, but stores our initialized variables.

In [6]:
### For example, lets initialize variable x

x = 1738

print("x has been set to " + str(x))

x has been set to 1738

In [7]:
### Print x

print(x)

1738

Issues arrise when we restart our kernel and attempt to run code with variables that have not been reinitialized.

If the kernel is reset, make sure to rerun code where variables are intialized.

In [ ]:
name = input("what is your name ")
print("Your name is "+ name)

In [ ]:
## We can also run code that accepts input

name = input("What is your name? ")

print("The name you entered is " + name)

It is important to note that Jupyter Notebooks have in-line cell execution.  This means that a prior executing cell must complete its operations prior to another cell being executed.  A cell still being executing is indicated by the [*] on the left-hand side of the cell.

In [ ]:
print("This won't print until all prior cells have finished executing.")

### Command vs. Edit Mode & Shortcuts

There is an edit and a command mode for jupyter notebooks.  The mode is easily identifiable by the color of the left border of the cell.

Blue = Command Mode.

Green = Edit Mode.

Command Mode can be toggled by pressing **esc** on your keyboard.

Commands can be used to execute notebook functions.  For example, changing the format of a markdown cell or adding line numbers.

Lets toggle line numbers while in º mode by pressing **L**.

#### Additional Shortcuts

There are a lot of shortcuts that can be used to improve productivity while using Jupyter Notebooks.

Here is a list:

![Jupyter Notebook Shortcuts](img/shortcuts.png)

### How do you install Jupyter Notebooks?

**Note:** *Coursera provides embedded jupyter notebooks within the course, thus the download is not a requirement unless you wish to explore jupyter further on your own computer.*

Official Installation Guide: https://jupyter.readthedocs.io/en/latest/install.html

Jupyter recommends utilizing Anaconda, which is a platform compatible with Windows, macOS, and Linux systems.  

Anaconda Download: https://www.anaconda.com/download/#macos

In [ ]:
print('My name is Saiful')

In [ ]:
import seaborn as sb
tips = sb.load_dataset('tips')
print(tips)
type(tips)

In [ ]:
name = input('¿Cual es tu nombre?')
print('Tu nombre es, ', name)

In [ ]:
x = 1996
print('1996 ha sido asignado a la variable X')

In [ ]:
print('Este codigo se ejecutara hasta el final')